name: portfolio
description: My Portfolio
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  transparent_image: ^1.0.0
  animated_text_kit: ^4.2.1
  url_launcher: ^6.0.4
  flutter_hooks: ^0.18.0
  flutter_lints: ^1.0.0
  blobs: ^1.2.0
  simple_animations: ^3.1.1
  flutter_staggered_grid_view: ^0.4.0
  responsive_framework: ^0.1.0
  timelines: ^0.1.0
  footer: ^0.0.3
  cupertino_icons: ^1.0.2
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Bobbers
      fonts:
        - asset: fonts/Bobbers-Personal.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Courgette
      fonts:
        - asset: fonts/Courgette-Regular.ttf
    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Regular.ttf