
name: CI

on:
  push:
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Portfolio
          ref: 'master'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config and push
        run: |
          git config user.name "Fa-d"
          git config user.email "fsadakathussain@gmail.com"
          git add .
          git commit -m "See ORIGIN_COMMIT from $GITHUB_REF"
          git remote add "origin" git@github.com:Fa-d/Fa-d.github.io.git
          git push -f origin main