name: CI

on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: Fa-d/Portfolio
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - name: Commit files
      run: |
        cd dist
        git init
        git config --local user.name "Fa-d"
        git config --local user.email "fsadakathussain@gmail.com"
        git branch -m master
        git add .
        git commit -m "Sync directory from source repository"

    - name: Push to target repository
      env:
        TARGET_REPO_PAT: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        git remote add origin https://${{ secrets.API_TOKEN_GITHUB }}@github.com/fa-d/Fa-d.github.io.git
        git branch -M main
        git remote rm origin
        git push -u origin main --force


