name: CI

on:
  push:
    branches: [master]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'dist'
        destination_repo: 'Fa-d/Fa-d.github.io'
        destination_folder: '.'
        user_email: 'fsadakathussain@gmail.com'
        user_name: 'Fa-d'
        commit_msg: 'Update the test files.'