
name: CI

on:
  push:
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'Fa-d/Portfolio'
          ref: 'master'
          token:  ${{ secrets.API_TOKEN_GITHUB}}
      - name: setup git config and push
        run: |
          mkdir ../../_temp/portf_dist
          cp -r dist ../../_temp/portf_dist
          ls ../../_temp/portf_dist
