
name: CI

on:
  push:
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'Fa-d/Portfolio'
          ref: 'master'
          token:  ${{ secrets.API_TOKEN_GITHUB}}
      - name: setup git config and push
        run: |
          mkdir ../../_temp/portf_dist
          cp -r dist ../../_temp/portf_dist
          cd ../../_temp/portf_dist/dist
          rm -rf .git/
          git init
          git config user.name "Fa-d"
          git config user.email "fsadakathussain@gmail.com"
          git remote set-url "origin" https://github.com/Fa-d/Fa-d.github.io.git
          git add .
          git commit -m "See ORIGIN_COMMIT from $GITHUB_REF"
          git push -f origin main